### ISSUE TITLE
Error [custom_components.vaillant.hub] Enable to fetch data from vaillant API

### ISSUE THREAD

**Issue by lh14576** [thomasgermain/vaillant-component#3]
Hi,
this component is awesome, so thanks for that! I am seeing constant errors with pymultimatic though:

`2020-03-20 08:28:21 ERROR (MainThread) [custom_components.vaillant.hub] Enable to fetch data from vaillant API
Traceback (most recent call last):
  File "/config/custom_components/vaillant/hub.py", line 45, in _update_system
    self.system = await system_coro
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/systemmanager.py", line 77, in get_system
    hvac_state = await hvac_state_req
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/systemmanager.py", line 582, in _call_api
    return await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/api/connector.py", line 171, in request
    payload=payload)
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/xxx/hvacstate/v1/overview`

Not sure if it's polling too often and if there is a setting to reduce polling frequency in order to try to fix this error. 
Once this error comes up it's repeating itself around every 2 minutes and the component is no longer updating the values.

**Comment by thomasgermain** [comment]
Hi,

thanks for your input :)

I'm currently working on a next version of the component, improving multiple points:
* better logging (http status from the response and response boy)
* auto re-login in case of some error

For now the only possible solution is to restart HA in order to be able to acquire a new session (cookie).

Indeed, poling is every 2 minutes (hardcoded), I can also add an option to configure it.

Thomas

**Comment by lh14576** [comment]
Thanks. I just realized that it starts working again once I connect with the official multimatic app. So it's probably an authorization issue.

Keep up the great work :)

**Comment by thomasgermain** [comment]
Ah yeah, it's not working for me because i'm using separate users for HA and the app.

**Comment by thomasgermain** [comment]
Hi,

I just released a new version. You should get rid of most of the problem, https://github.com/thomasgermain/vaillant-component/releases/tag/1.1.0

**Comment by lh14576** [comment]
Hi,
thanks for the new version. I am still getting a lot of errors unfortunately and the component stops updating. Here are the 2 errors I am receiving:
`Protokolldetails ( ERROR )
Logger: homeassistant.core
Source: custom_components/vaillant/hub.py:58
First occurred: 3. April 2020, 21:23:07 (56 occurrences)
Last logged: 7:34:05

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/vaillant/hub.py", line 51, in _hvac_update
    await self._manager.request_hvac_update()
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/systemmanager.py", line 546, in request_hvac_update
    state = mapper.map_hvac_sync_state(await self._call_api(urls.hvac))
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/systemmanager.py", line 582, in _call_api
    return await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/api/connector.py", line 171, in request
    payload=payload)
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21193100202609620938017049N8/hvacstate/v1/overview

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/vaillant/hub.py", line 58, in _hvac_update
    exec_info=True,
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1390, in warning
    self._log(WARNING, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'exec_info'`

`Logger: custom_components.vaillant.hub
Source: custom_components/vaillant/hub.py:68
First occurred: 3. April 2020, 21:20:03 (276 occurrences)
Last logged: 7:39:48

Unable to fetch data from vaillant API, API says: {'errorCode': 'NullPointerException'}, status: 500
Traceback (most recent call last):
  File "/config/custom_components/vaillant/hub.py", line 68, in _update_system
    self.system = await self._manager.get_system()
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/systemmanager.py", line 77, in get_system
    hvac_state = await hvac_state_req
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/systemmanager.py", line 582, in _call_api
    return await self._connector.request(method, url, payload)
  File "/usr/local/lib/python3.7/site-packages/pymultimatic/api/connector.py", line 171, in request
    payload=payload)
pymultimatic.api.error.ApiError: Cannot get https://smart.vaillant.com/mobile/api/v4/facilities/21193100202609620938017049N8/hvacstate/v1/overview`

**Comment by thomasgermain** [comment]
Hi,

thanks for you input.
First, you should not put your serial number (while I don't really see any problem). I edited your post.

So, as you saw, there are two errors. I can fix something for the first one (I actually did a typo -_-). But it will just improve log. It seems the API is not reachable.

Real error is actually the second one and I cannot do anything about that, the API is returning `{'errorCode': 'NullPointerException'}`. (If you are developer, you know what `NullPointerException` means :) Otherwise, it means this is a bug at API side.)

**Comment by lh14576** [comment]
thanks for the edit. I didn't intend to provide my serial no. I was just a little quick in copy-pasting the error messages without really looking into those, sorry for that.

Let me see if I can get to the bottom of the null pointer exception trying to find some kind of pattern that reproduces this error.

**Comment by lh14576** [comment]
Running without error for 24h+ using a dedicated user account just for homeassistant. Just in case someone is running into similar problems.

**Comment by thomasgermain** [comment]
I'm glad it's working 😊
